packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@apollo/protobufjs': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@serialport/bindings-cpp': true
  '@swc/core': true
  esbuild: true
  less: true
  midi: true
  nx: true
  sharp: true
  unrs-resolver: true
  usb: true
minimumReleaseAgeExclude:
  - '@formatjs/cli-native-darwin-arm64@1.1.1'
  - '@formatjs/cli-native-linux-arm64@1.2.1'
  - '@formatjs/cli-native-linux-x64@1.1.1'
  - '@formatjs/cli-native-win32-x64@1.1.2'
  - '@formatjs/cli@6.16.6'
