packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@apollo/protobufjs': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@serialport/bindings-cpp': true
  '@swc/core': true
  cpu-features: true
  esbuild: true
  less: true
  midi: true
  nx: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
  usb: true
minimumReleaseAge: 2880 # 2 days in minutes
