fragment VendorFields on FixtureVendorDto {
  publicId
  name
  createdAt
  updatedAt
}

fragment FixtureChannelAssignmentFields on FixtureChannelAssignmentDto {
  publicId
  channelNumber
  createdAt
  updatedAt
}

fragment FixtureChannelRangeFields on FixtureChannelRangeDto {
  publicId
  dmxStart
  dmxEnd
  description
  createdAt
  updatedAt
}

fragment FixtureChannelDefinitionFields on FixtureChannelDefinitionDto {
  publicId
  name
  preset
  fixtureChannelRanges {
    ...FixtureChannelRangeFields
  }
  createdAt
  updatedAt
}

fragment FixtureChannelModeFields on FixtureChannelModeDto {
  publicId
  name
  fixtureChannelAssignments {
    ...FixtureChannelAssignmentFields
  }
  createdAt
  updatedAt
}

fragment FixtureFields on FixtureDto {
  publicId
  name

  fixtureChannelDefinitions {
    ...FixtureChannelDefinitionFields
  }

  fixtureChannelModes {
    ...FixtureChannelModeFields
  }

  fixtureVendor {
    ...VendorFields
  }

  createdAt
  updatedAt
}

query GetFixtures {
  fixtures {
    ...FixtureFields
  }
}

query GetFixture($fixtureId: UUID!) {
  fixture(fixtureId: $fixtureId) {
    ...FixtureFields
  }
}

query GetVendors {
  vendors {
    ...VendorFields
  }
}
