fragment VendorFields on VendorResponseDto {
  externalId
  name
  createdAt
  updatedAt
}

fragment ChannelAssignmentFields on ChannelAssignmentDto {
  channelMode
  channelNumber
  createdAt
  externalId
  preset
  updatedAt
}

fragment FixtureFields on FixtureResponseDto {
  externalId
  name

  vendor {
    ...VendorFields
  }

  channelAssignments {
    ...ChannelAssignmentFields
  }

  createdAt
  updatedAt
}

query GetFixtures {
  fixtures {
    ...FixtureFields
  }
}

query GetFixture($fixtureId: UUID!) {
  fixture(fixtureId: $fixtureId) {
    ...FixtureFields
  }
}

query GetVendors {
  vendors {
    ...VendorFields
  }
}
