input ChannelValuesInput {
  """The list of DMX channel values"""
  dmxValues: [DmxValueInput!]! = [{channel: 1, value: 127}]
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

input DmxValueInput {
  """The DMX channel number (1-512)"""
  channel: Int!

  """The DMX channel value (0-255)"""
  value: Int!
}

type FixtureChannelAssignmentDto {
  """The number of the channel assignment"""
  channelNumber: Int!

  """The date and time when the entity was created"""
  createdAt: DateTime!

  """The public id, unique identifier of the entity"""
  publicId: UUID!

  """The date and time when the entity was last updated"""
  updatedAt: DateTime!
}

type FixtureChannelDefinitionDto {
  """The date and time when the entity was created"""
  createdAt: DateTime!

  """The channel assignments of the channel mode"""
  fixtureChannelAssignments: [FixtureChannelAssignmentDto!]!

  """The channel ranges of the channel definition"""
  fixtureChannelRanges: [FixtureChannelRangeDto!]!

  """The name of the channel definition"""
  name: String!

  """The order of the channel definition"""
  order: Int!

  """The preset of the channel assignment"""
  preset: FixtureChannelPreset!

  """The public id, unique identifier of the entity"""
  publicId: UUID!

  """The date and time when the entity was last updated"""
  updatedAt: DateTime!
}

type FixtureChannelModeDto {
  """The date and time when the entity was created"""
  createdAt: DateTime!

  """The channel assignments of the channel mode"""
  fixtureChannelAssignments: [FixtureChannelAssignmentDto!]!

  """The name of the channel mode"""
  name: String!

  """The order of the channel mode"""
  order: Int!

  """The public id, unique identifier of the entity"""
  publicId: UUID!

  """The date and time when the entity was last updated"""
  updatedAt: DateTime!
}

"""The preset of a fixture channel assignment"""
enum FixtureChannelPreset {
  Custom
  IntensityAmber
  IntensityBlue
  IntensityDimmer
  IntensityGreen
  IntensityMasterDimmer
  IntensityRed
  IntensityUV
  IntensityWhite
  ShutterStrobeFastSlow
  ShutterStrobeSlowFast
}

type FixtureChannelRangeDto {
  """The date and time when the entity was created"""
  createdAt: DateTime!

  """The description of the channel range"""
  description: String!

  """The DMX end channel of the channel range"""
  dmxEnd: Int!

  """The DMX start channel of the channel range"""
  dmxStart: Int!

  """The public id, unique identifier of the entity"""
  publicId: UUID!

  """The date and time when the entity was last updated"""
  updatedAt: DateTime!
}

type FixtureDto {
  """The date and time when the entity was created"""
  createdAt: DateTime!

  """The channel definitions of the fixture"""
  fixtureChannelDefinitions: [FixtureChannelDefinitionDto!]!

  """The channel modes of the fixture"""
  fixtureChannelModes: [FixtureChannelModeDto!]!

  """The vendor of the fixture"""
  fixtureVendor: FixtureVendorDto!

  """The name of the fixture"""
  name: String!

  """The public id, unique identifier of the entity"""
  publicId: UUID!

  """The date and time when the entity was last updated"""
  updatedAt: DateTime!
}

type FixtureVendorDto {
  """The date and time when the entity was created"""
  createdAt: DateTime!

  """The name of the vendor"""
  name: String!

  """The public id, unique identifier of the entity"""
  publicId: UUID!

  """The date and time when the entity was last updated"""
  updatedAt: DateTime!
}

input FixtureVendorInput {
  """The name of the vendor"""
  name: String

  """The public ID of the vendor (used for updates)"""
  publicId: UUID
}

type MidiDeviceDto {
  """The name of the MIDI device"""
  name: String!

  """The port number of the MIDI device"""
  port: Int!
}

type MidiDevicesDto {
  """The list of MIDI input devices"""
  inputDevices: [MidiDeviceDto!]!

  """The list of MIDI output devices"""
  outputDevices: [MidiDeviceDto!]!
}

type Mutation {
  """Close the specified MIDI ports"""
  closePorts: Boolean

  """test dmx resolver"""
  dmxTest(channelValues: ChannelValuesInput!): String!

  """Open the specified MIDI ports"""
  openPorts(openPortsDto: OpenPortsInput!): Boolean

  """update an existing fixture"""
  updateFixture(input: UpdateFixtureInput!): FixtureDto!
}

input OpenPortsInput {
  """The MIDI input port number to open"""
  inputPort: Int! = 1

  """The MIDI output port number to open"""
  outputPort: Int! = 1
}

type Query {
  """get fixture by external id"""
  fixture(fixtureId: UUID!): FixtureDto

  """get all fixture vendors"""
  fixtureVendors: [FixtureVendorDto!]!

  """get all fixtures"""
  fixtures: [FixtureDto!]!

  """Get the list of MIDI input and output devices"""
  getMidiDevices: MidiDevicesDto!
}

"""
A field whose value is a generic Universally Unique Identifier: https://en.wikipedia.org/wiki/Universally_unique_identifier.
"""
scalar UUID

input UpdateFixtureInput {
  """The name of the fixture"""
  name: String

  """The public ID of the fixture"""
  publicId: UUID!

  """The vendor of the fixture"""
  vendor: FixtureVendorInput
}