/* eslint-disable no-console -- CLI script that prints generation output */
import * as schema from '@/db/schema';
import { getTableName } from 'drizzle-orm';
import { getTableConfig, PgTable as PgTableClass } from 'drizzle-orm/pg-core';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// The `erd` Nx target runs with cwd = apps/backend, so resolve relative to cwd.
const DEFAULT_OUT = resolve(process.cwd(), 'docs/database-schema.md');

interface ErdRelationship {
  fromTable: string;
  toTable: string;
  label: string;
}

interface ErdEntity {
  table: string;
  attributes: ErdAttribute[];
}

interface ErdAttribute {
  name: string;
  sqlType: string;
  notNull: boolean;
  isPrimaryKey: boolean;
  isForeignKey: boolean;
}

function isPgTable(value: unknown): value is PgTableClass {
  return value instanceof PgTableClass;
}

function collectRelationships(): ErdRelationship[] {
  const relationships: ErdRelationship[] = [];

  for (const value of Object.values(schema)) {
    if (!isPgTable(value)) {
      continue;
    }

    const childConfig = getTableConfig(value);
    const childTable = childConfig.name;

    for (const fk of childConfig.foreignKeys) {
      const reference = fk.reference();
      const parentTable = getTableName(reference.foreignTable);
      const localColumn = reference.columns[0]?.name ?? 'id';
      relationships.push({
        fromTable: parentTable,
        toTable: childTable,
        label: localColumn,
      });
    }
  }

  return relationships;
}

function collectEntities(): { entities: ErdEntity[]; ukColumnsByTable: Map<string, Set<string>> } {
  const entities: ErdEntity[] = [];
  const ukColumnsByTable = new Map<string, Set<string>>();

  for (const value of Object.values(schema)) {
    if (!isPgTable(value)) {
      continue;
    }

    const config = getTableConfig(value);
    const fkColumns = new Set(config.foreignKeys.flatMap(fk => fk.reference().columns.map(column => column.name)));
    // Inline primary keys (e.g. `.primaryKey()`) are not surfaced via
    // `config.primaryKeys`; read the per-column `primary` flag instead.
    const ukColumns = new Set(config.uniqueConstraints.flatMap(uc => uc.columns.map(column => column.name)));
    for (const column of config.columns) {
      if ((column as { isUnique?: boolean }).isUnique) {
        ukColumns.add(column.name);
      }
    }
    ukColumnsByTable.set(config.name, ukColumns);

    const attributes: ErdAttribute[] = config.columns.map(column => ({
      name: column.name,
      sqlType: column.getSQLType(),
      notNull: column.notNull,
      isPrimaryKey: (column as unknown as { primary: boolean }).primary,
      isForeignKey: fkColumns.has(column.name),
    }));

    entities.push({ table: config.name, attributes });
  }

  return { entities, ukColumnsByTable };
}

function toMermaidType(sqlType: string): string {
  // Mermaid attribute types must start with an alphabetic character.
  // Map common PostgreSQL types to simple identifiers; fall back to a sanitized form.
  const base = sqlType.toLowerCase().replace(/[^a-z]/g, '');
  return base.length > 0 ? base : 'unknown';
}

function toMermaid(
  relationships: ErdRelationship[],
  entities: ErdEntity[],
  ukColumnsByTable: Map<string, Set<string>>,
): string {
  const lines: string[] = ['erDiagram'];

  for (const { fromTable, toTable, label } of relationships) {
    // fromTable is the "one" side, toTable is the "many" side (it holds the FK).
    lines.push(`    ${fromTable} ||--o{ ${toTable} : "${label}"`);
  }

  for (const { table, attributes } of entities) {
    lines.push(`    ${table} {`);
    for (const attr of attributes) {
      const keys: string[] = [];
      if (attr.isPrimaryKey) {
        keys.push('PK');
      }
      if (attr.isForeignKey) {
        keys.push('FK');
      }
      if (ukColumnsByTable.get(table)?.has(attr.name) && !attr.isPrimaryKey) {
        keys.push('UK');
      }
      const keySuffix = keys.length > 0 ? ` ${keys.join(',')}` : '';
      const type = toMermaidType(attr.sqlType);
      lines.push(`        ${type} ${attr.name}${keySuffix}`);
    }
    lines.push('    }');
  }

  return lines.join('\n');
}

function main(): void {
  const relationships = collectRelationships();
  const { entities, ukColumnsByTable } = collectEntities();
  const mermaid = toMermaid(relationships, entities, ukColumnsByTable);

  const outIndex = process.argv.indexOf('--out');
  const explicitOut = outIndex !== -1 ? process.argv[outIndex + 1] : undefined;
  const outPath = explicitOut ?? DEFAULT_OUT;
  const content = `# Database Schema\n\n> Auto-generated by \`nx run backend:erd\`. Do not edit manually.\n\n\`\`\`mermaid\n${mermaid}\n\`\`\`\n`;
  mkdirSync(resolve(outPath, '..'), { recursive: true });
  writeFileSync(outPath, content);
  console.log(`Wrote Mermaid ER diagram to ${outPath}`);
}

main();
