import ApolloWrapper from '@/lib/graphql/apollo-wrapper';
import IntlWrapper from '@/lib/i18n/intl-wrapper';
import { ReactNode } from 'react';
import './global.css';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

type LayoutProperties = {
  params: Promise<{ locale: string }>;
  children: ReactNode;
};

const RootLayout = async ({ params, children }: LayoutProperties) => {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body>
        <ApolloWrapper>
          <IntlWrapper locale={locale}>{children}</IntlWrapper>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
