info:
  name: channel-values
  type: http
  seq: 1

http:
  method: POST
  url: "{{backendUrl}}/api/dmx/channel-values"
  body:
    type: json
    data: |-
      {
        "dmxValues": [
          {
            "channel": 1,
            "value": 255
          },
          {
            "channel": 3,
            "value": 127
          }
        ]
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
