info:
  name: project
  type: graphql
  seq: 7

graphql:
  method: POST
  url: "{{backendUrl}}/graphql"
  auth: inherit
  body:
    query: |
      query($publicId: UUID!) {
        project(publicId: $publicId) {
          createdAt
          name
          projectFixtures {
            channelMode {
              createdAt
              fixtureChannelAssignments {
                channelNumber
              }
              name
              publicId
              updatedAt
            }
            createdAt
            fixture {
              createdAt
              fixtureVendor {
                createdAt
                name
                publicId
                updatedAt
              }
              name
              publicId
              updatedAt
            }
            publicId
            startAddress
            updatedAt
          }
          publicId
          updatedAt
        }
      }
    variables: |
      {
        "publicId": null
      }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
